server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    group:
      "local": "local, jwt, oauth"
    active: local
  # 개발 데이터베이스 연결
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: ENC(+hoiZ9yo77g+QhmKaryQtnwc4CaX9dxu)

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화 : 100 ~ 1000 권장
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정 (default 인 true 에서는 interceptor, controller, view 까지 살아있음)

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB 제한

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.example: debug # todo 패키지 수정

feign:
  client:
    config:
      default: # 전역 처리
        connectTimeout: 5000 # 3-way handshake 시간 제한
        readTimeout: 5000

jasypt:
  encryptor:
    password: ${PASSWORD}

naver-cloud-sms:
  accessKey: ENC(LMf2j10vy65ZbmkRIu2r1ehtQ5CFlh4itsgIFR9lklg=)
  secretKey: ENC(uo0k2A/MWqIjM6OPjLWO2Pc5RmmmLKikm+nVuumk6o64WLkikywyMc6vTxMdDgQmlNzCf4+aZ1w=)
  serviceId: ncp:sms:kr:312158415801:i_like_cloud
  senderPhone: "01059111911"